version: '3.8'

services:
  ecommerce-monolith:
    build: .
    container_name: ecommerce-monolith
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xmx512m -Xms256m
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    
  # Para desenvolvimento futuro - PostgreSQL
  # postgres:
  #   image: postgres:15
  #   container_name: ecommerce-postgres
  #   environment:
  #     POSTGRES_DB: ecommerce
  #     POSTGRES_USER: ecommerce_user
  #     POSTGRES_PASSWORD: ecommerce_pass
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped

# volumes:
#   postgres_data:
